### ISSUE TITLE
shasum: command not found

### ISSUE THREAD

**Issue by micahthomas** [irondash/cargokit#57]
Context:
I ran into `shasum: command not found` error from file `cargokit/run_build_tool.sh:55` on ArchLinux.
I was setting up an example app from the `flutter_rust_bridge` project.

Issue:
The `run_build_tool.sh` is looking for `shasum` command, but on archlinux it is called `sha1sum`.

To reproduce:
- ArchLinux
- Rust stable toolchain
- Flutter stable
```bash
cargo install 'flutter_rust_bridge_codegen@^2.0.0-dev.21' && \
                                    flutter_rust_bridge_codegen create my_app && cd my_app && flutter run -v
```

Relevant output `flutter run -v`
```bash
...
[   +1 ms] /home/micah/projects/my_app/rust_builder/cargokit/run_build_tool.sh: line 55: shasum: command not found
...
[        ] Exception: Build process failed
[   +4 ms] "flutter run" took 12,405ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:790:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +35 ms] ensureAnalyticsSent: 34ms
[        ] Running 1 shutdown hook
[   +5 ms] Shutdown hooks complete
[        ] exiting with code 1
```

Temporary fix:
```bash
ln -s /usr/bin/sha1sum /usr/bin/shasum
```

**Comment by micahthomas** [comment]
I am happy to make a PR that checks for either `sha1sum` or `shasum` if that will be an acceptable long term fix.

**Comment by knopp** [comment]
Hi, a PR would be welcome :)
